### ISSUE TITLE
chunking schema for analysis-ready?

### ISSUE THREAD

**Issue by Lkruitwagen** [google-research/arco-era5#12]
Hey guys! Love to see this effort.

Quick question about the chunking schema you're planning for an analysis-ready corpus. Will you keep the native ERA5 chunking, i.e. `{'time':1}`? Are you chunking variables together?

With [h2ox](https://github.com/H2Oxford/h2ox-data) we've chunked hourly ERA5-land in blocks of 4-years with some moderate spatial aggregation, e.g. 5 degrees. Our main use case is for quick/easy retrieval of timeseries. Would be good to know what you guys are thinking for the chunking schema here!

**Comment by alxmrs** [comment]
We did do an internal chunking experiment where we prioritized querying by time. This revealed the inherent Zarr-specific tradeoffs where you have to prioritize between space and time (or, between dimensions A vs dimensions B). Given the other use cases we want to support for this dataset, our plan is to prefer the existing chunking scheme (the whole globe at every hour) and to support timeseries like analysis with BigQuery.

**Comment by Lkruitwagen** [comment]
Thanks for the update. Glad to see this project going somewhere!
