### ISSUE TITLE
Automatically ingest raw ERA5 data as soon as it's available from ECMWF.

### ISSUE THREAD

**Issue by alxmrs** [google-research/arco-era5#19]
Ideally, we'd like to make sure that this repository has new raw data from ECMWF as soon as it's available. For at least a few dataset, Copernicus makes new data available on a [daily cadence](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=overview). 

## Implementation Notes
Let's modify our existing `weather-dl` scripts to try to ingest new data from CDS on on a cron via Github Actions. Here, we should modify the config on every run to extend it to the current date. This may require we modify the config parser of `weather-dl` a bit first https://github.com/google/weather-tools/issues/267.

**Comment by dabhicusp** [comment]
Hello @alxmrs,

I've already incorporated a similar functionality that facilitates data download within a "monthly span." Furthermore, I've successfully utilized the code from PR #36 to perform data downloads, and it worked flawlessly.

The data I downloaded using of the above script was found in the below directory:
`gs://gcp-public-data-arco-era5/raw/ERA5GRIB/HRES/Daily/2023/202305**_hres_**.grb2`
`gs://gcp-public-data-arco-era5/raw/ERA5GRIB/HRES/Month/2023/202305**_hres_**.grb2`
`gs://gcp-public-data-arco-era5/raw/date-variable-pressure_level/2023/07/*`
`gs://gcp-public-data-arco-era5/raw/date-variable-single_level/2023/07/*`

If everything looks good to you, shall we consider closing this issue?

**Comment by alxmrs** [comment]
Yes! This LGTM. Closing as fixed. :)
