### ISSUE TITLE
Add TISR 212 and LSM 172

### ISSUE THREAD

**Issue by loliverhennigh** [google-research/arco-era5#25]
It would be great to see if this dataset could be used to train machine learning models such as graphcast. There are a couple of variable missing though,
![Screenshot from 2023-03-07 15-00-09](https://user-images.githubusercontent.com/4978408/223573611-12258d00-edae-44a8-b265-9fe68dd0b45c.png)
(taken from here, https://arxiv.org/pdf/2212.12794.pdf) I think the two missing fields are Incident solar radiation and land sea mask. Any interest in including these or even trying to get all the era5 variables available.

**Comment by alxmrs** [comment]
Yes, definitely stay tuned. This is within our immediate plans :)

**Comment by alxmrs** [comment]
We're going to be a bit slow in updating docs & code on this, but please check `gs://gcp-public-data-arco-era5/ar`. It should have what you're looking for 😉 .
