### ISSUE TITLE
Document "single-level-surface.zarr" in README

### ISSUE THREAD

**Issue by mlshapiro** [google-research/arco-era5#26]
The documentation is really helpful, thank you!

I was looking for surface pressure (to compute pressure on the model levels) and found there is a separate store `single-level-surface.zarr` in [1-Model-Levels-Walkthrough.ipynb](https://github.com/google-research/arco-era5/blob/50f85af55794d1e1d79d48bb825a470fdfffd7a9/docs/1-Model-Levels-Walkthrough.ipynb)

It would be great if this was included in the README below the [Model Level Wind](https://github.com/google-research/arco-era5#model-level-wind) section.

**Comment by alxmrs** [comment]
Thanks, this is certainly an oversight!
