### ISSUE TITLE
Add surface level raw download configs.

### ISSUE THREAD

**Issue by alxmrs** [google-research/arco-era5#33]
> I couldn't find the config files in /raw -- perhaps these need to be added too?

Will follow up in a future issue.

_Originally posted by @alxmrs in https://github.com/google-research/arco-era5/issues/27#issuecomment-1581348993_

**Comment by dabhicusp** [comment]
I confirmed that config files of variables which are used in this zarr `gs://gcp-public-data-arco-era5/co/single-level-surface.zarr` is `missing`. Other than this we have all of the config file of all variables which are part of this directory `gs://gcp-public-data-arco-era5/co/`.

We need config file for these two variables:
   1. ****_hres_lnsp.grb2 
   2. ****_hres_zs.grb2

**Comment by dabhicusp** [comment]
I have downloaded the data using of the newly added config so now I can clearly says it is fine and you should have to close this issue.
Data downloaded: `lnsp` and `zs` variable in the [given bucket](https://pantheon.corp.google.com/storage/browser/gcp-public-data-arco-era5/raw/ERA5GRIB/HRES/Month/2023?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22,%22s%22:%5B(%22i%22:%22objectListDisplayFields%2FtimeCreated%22,%22s%22:%221%22),(%22i%22:%22displayName%22,%22s%22:%220%22)%5D))&cloudshell=false&mods=-staging_coliseum&project=gcp-public-data-signals&prefix=&forceOnObjectsSortingFiltering=true).

**Comment by alxmrs** [comment]
Closing as fixed!
