### ISSUE TITLE
time unit error when opening single-level-forecast.zarr-v2

### ISSUE THREAD

**Issue by amarant** [google-research/arco-era5#59]
Hi,
If I try to open the single-level-forecast.zarr-v2 with :

```python
sl_forecasts = xr.open_zarr(
    'gs://gcp-public-data-arco-era5/co/single-level-forecast.zarr-v2/', 
    chunks={'time': 48},
    consolidated=True,
)
```

I get the error :
`
ValueError: Failed to decode variable 'valid_time': unable to decode time units 'hours since 1900-01-01 06:00:00' with "calendar 'proleptic_gregorian'". Try opening your dataset with decode_times=False or installing cftime if it is not installed.
`
But cftime is already installed.

Also the time unit seems strange : `hours since 1900-01-01T06:00:00.000000`, it is probably in days from a more recent date.

So adding `decode_times=False` and doing 
```
units, reference_date = sl_forecasts.time.attrs['units'].split('since')
sl_forecasts['time'] = pd.date_range(start=reference_date, periods=sl_forecasts.sizes['time'], freq='H')
```
would be wrong.

Any idea how we can open the dataset with the correct time ?

Thanks.

**Comment by DarshanSP19** [comment]
Hey @amarant Can you please try again? We have added a fix.
Thanks.

**Comment by amarant** [comment]
It works now, thanks.

**Comment by alxmrs** [comment]
Wow, great work Sahil and Darshan!
