### ISSUE TITLE
Could surface solar radiation be added?

### ISSUE THREAD

**Issue by jacobbieker** [google-research/arco-era5#64]
Hi,
Really great work! Its nice being able to stream in all this ERA5 data. I was wondering if some more surface solar radiation variables could be added to this? The reason for this would be to help with renewable energy generation forecasting, specifically PV/Solar generation, and training models to forecast those.

**Comment by shoyer** [comment]
Have you looked at the 0.25 degree `full_37-1h-0p25deg-chunk-1.zarr-v3` dataset?
https://github.com/google-research/arco-era5?tab=readme-ov-file#full_37-1h-0p25deg-chunk-1zarr-v3

It includes a bunch of solar radiation variables, which I believe should cover what you're looking for: clear_sky_direct_solar_radiation_at_surface, surface_net_solar_radiation, surface_net_solar_radiation_clear_sky, surface_solar_radiation_downward_clear_sky, surface_solar_radiation_downwards, toa_incident_solar_radiation, top_net_solar_radiation, top_net_solar_radiation_clear_sky, total_sky_direct_solar_radiation_at_surface.

**Comment by jacobbieker** [comment]
Oh, no, I hadn't seen that. Yeah, that has what I would want in it. Thanks!
