### ISSUE TITLE
ERA5 zarr file on Google Cloud 

### ISSUE THREAD

**Issue by yuliang954** [google-research/arco-era5#71]
In the neuralgcm_inference demo, era5 data provided through Goggle cloud is inverted along the latitude axis on some days, for example, on 1981-03-16.

**Comment by shoyer** [comment]
To reproduce:
```
import gcsfs
import xarray

gcs = gcsfs.GCSFileSystem(token='anon')
path = 'gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3'
full_era5 = xarray.open_zarr(gcs.get_mapper(path), chunks=None)

# correct data
full_era5.sea_surface_temperature.sel(time='2020-01-01T00').plot.imshow(
    x='longitude', y='latitude', size=3, aspect=2)

# flipped data
full_era5.sea_surface_temperature.sel(time='1981-03-16T00').plot.imshow(
    x='longitude', y='latitude', size=3, aspect=2)
```
![image](https://github.com/google-research/arco-era5/assets/1217238/f501a1ba-7818-48eb-b33e-4fbb76fc6a8f)
![image](https://github.com/google-research/arco-era5/assets/1217238/6d9db5c1-f920-4bb5-b3a8-93085ba96f04)

**Comment by shoyer** [comment]
This is a duplicate issue, so closing this in favor of #70
