### ISSUE TITLE
Missing v_component_of_wind and zarr metadata

### ISSUE THREAD

**Issue by markmbaum** [google-research/arco-era5#76]
I noticed that the dataset here: https://console.cloud.google.com/storage/browser/gcp-public-data-arco-era5/ar/1959-2023_01_10-full_37-1h-1440x721.zarr

is missing the `v_component_of_wind` variable. It's also missing the usual zarr metadata files (`.zattrs`, `.zgroup`, `.zmetadata`) and can't be opened in the usual way. For example,
```
import xarray as xr

xr.open_zarr("gs://gcp-public-data-arco-era5/ar/1959-2023_01_10-full_37-1h-1440x721.zarr")
```
raises `FileNotFoundError` because it cant find those metadata files.

**Comment by shoyer** [comment]
Is there a reason you're trying to access this particular data? It is not described in the README. I think this is a partially written test version of data that should probably be deleted.

The full version of this dataset is in:
`gs://gcp-public-data-arco-era5/ar/1959-2023_01_10-full_37-1h-0p25deg-chunk-1.zarr`

**Comment by markmbaum** [comment]
No I don't need this particular dataset. I was just looking around, noticed it, and thought I would mention it.
