### ISSUE TITLE
xarray.open_zarr is reading only NANs

### ISSUE THREAD

**Issue by edur409** [google-research/arco-era5#83]
Hi there,

I tried these simple lines and my plot is empty.  On closer inspection, the array is full of NaN values. What could be the issue?  Best regards.

import xarray

ar_full_37_1h = xarray.open_zarr(
    'gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3',
    chunks=None,
    storage_options=dict(token='anon'),
)

ar_full_37_1h.geopotential[1,0,:,:].plot()

**Comment by yingkaisha** [comment]
Add to this issue, it seems that `full_37-1h-0p25deg-chunk-1.zarr-v3` cannot be accessed properly. Didn't test all but `1959-2022-6h-1440x721.zarr` can be opened without NaNs

**Comment by dabhicusp** [comment]
Hello @edur409,
The dataset(`gs://gcp-public-data-arco-era5/ar/full\_37-1h-0p25deg-chunk-1.zarr-v3`) contains data ranging from `1940-01-01` to `2024-05-31` (three months behind the current month). Therefore, if you execute the command `ar_full_37_1h.geopotential[1,0,:,:].plot()`, it will attempt to access the first date's data (`1900-01-01 T01:00:00`), which is not available in the dataset. Consequently, you will encounter `NaN` values.

To resolve this issue, please ensure that you only access data within the specified range of `1940-01-01` to `2024-05-31` (three months behind the current month).

The readme.md file will be updated shortly to reflect this data information.

Please let me know if you have any questions.

P.S:  close this issue if your query is resolved 😄.

**Comment by yingkaisha** [comment]
Resolved for me. Thank you.

**Comment by edur409** [comment]
Silly me! I should have checked at least the latest index of the array too.  Thank you!
